name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: 'postgres'
          POSTGRES_USER: 'user'
          POSTGRES_PASSWORD: '4904'
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: JDK Set Up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get Gradle Execution Permission
        run: chmod +x gradlew

      - name: Get Github Action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Run Integration Test
        run: ./gradlew integrationTest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 본인 리전으로 변경

      - name: Authorize IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-name security_group --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2  # 본인 리전으로 변경

      - name: Set Up SSH
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          printf "%s" "${{ secrets.KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts || true

      - name: Deploy to EC2
        run: |
          ssh -i $HOME/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/e-commerce-backend
            git pull origin main
            ./gradlew clean bootJar
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
          EOF

      - name: Remove IP from Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress --group-name security_group --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2